import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import ContactMe from '../components/ContactMe'
// import WorkExperience from '../components/WorkExperience'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'

export default function Home() {
  return (
    <div className='bg-black text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-800 scrollbar-thumb-red-500'>
      <Head>
        <title>Frankky's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className=''>
       <Header />
   </span>
       <span id='hero' className='snap-center '>
        <Hero/>
       </span  >
       <span id='about' className='snap-center'>
        <About/>

       </span>
       <span id='experience' className='snap-center'>
        <WorkExperience/>
        </span>

        <span id='Skills' className='snap-start'> 
          <Skills/>
        </span>
        <span id='projects' className='snap-center'>
             <Projects/>
        </span>
        <span>
          <ContactMe/>
        </span>
        
        <Link href="#hero">

         <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <Image className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer' src="https://hashnode.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fres%2Fhashnode%2Fimage%2Fupload%2Fv1670987023837%2FNmI2YBFN2.png%3Fw%3D500%26h%3D500%26fit%3Dcrop%26crop%3Dfaces%26auto%3Dcompress%2Cformat%26format%3Dwebp&w=1080&q=75" alt="" />
          </div>
         </footer>
        </Link>
       
    </div>
  )
}
